name: CI
on: [push, pull_request]

jobs:
  macOS-latest:
    runs-on: macOS-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.20.x

      - name: Build
        run: |
          make tools
          make lint
          make test
          make build

  windows-latest:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.20.x

      - name: Build
        run: |
          make tools
          make lint
          make test
          make build
